devices: # Пример добавления устройств
  MIKROTIK-MSK-1:
    host: "192.168.88.1"
    username: "admin"
    password: "admin"
    port: 22
    description: "MSK office"
    
  MIKROTIK-MSK-2:
    host: "192.168.88.2"
    username: "admin"
    password: "admin"
    port: 22
    description: "MSK warehouse"
    
  MIKROTIK-SPB-1:
    host: "192.168.88.3"
    username: "admin"
    password: "admin"
    port: 22
    description: "SPB"