scheduler:
  version_check:
    enabled: false
    time: "09:00"
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
    telegram_report: true
  
  update_check:
    enabled: true
    time: "09:00"
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
    telegram_report: true
  
  auto_update:
    enabled: false
    time: "23:00"
    days: ["monday", "tuesday", "wednesday", "thursday", "friday", "sunday"]
    devices: ["MIKROTIK-MSK-1", "MIKROTIK-SPB-1"]  # Перечислить все нужные устройства или "all" 
    backup_before_update: true
    telegram_report: true
    
  auto_backup:
    enabled: true
    time: "02:00"
    days: ["sunday"]
    devices: ["all"]
    telegram_report: true


notifications:
  telegram_on_success: true
  telegram_on_failure: true
  console_logging: false
  log_to_file: true